- name: configures ansible node
  hosts: all
  become: true
  vars:
    - admin_password: 'ansible123!'

  tasks:

    - name: Configure user 'devops'
      ansible.builtin.user:
        name: devops
        shell: /bin/bash
        password: "{{ 'ansible123!' | password_hash('sha512', 'mysecretsalt') }}"
        groups: wheel
        append: yes

    - name: enable sshd password auth
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: '^PasswordAuthentication'
        line: >-
          PasswordAuthentication yes

    - name: restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted

    - name: Install required packages
      dnf:
        name:
          - vim
          - git
          - wget
          - nano
          - tree
          - sshpass
          - tmux
          - emacs
          - gcc
          - bind-utils
        state: present
      register: dnf_check
      until: dnf_check is not failed
      retries: 4
      delay: 5

    - name: install code server
      vars:
        username: 'devops'
      include_tasks: "./roles/code_server/tasks/codeserver.yml"

    # - name: remove dnf automatic
    #   package:
    #     name: dnf-automatic
    #     state: absent
   
    # Stop dnf auto updates
    - name: disable dnf automatic services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      loop:
        - dnf-automatic.timer

    - name: automatic.conf disable downloads
      ansible.builtin.lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: '^download_updates'
        line: download_updates = no

    - name: automatic.conf disable updates
      ansible.builtin.lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: '^apply_updates'
        line: apply_updates = no

    - name: Disable RHUI repos
      ansible.builtin.command: >
        dnf config-manager --set-disabled rhui*