---
- name: configures mesh node
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: check variables are defined and not empty before building image
      ansible.builtin.fail:
        msg: "{{ item }} is undefined or empty. Please check your extra vars file"
      when: not lookup('vars', item) or lookup('vars', item) is undefined
      loop:
        - offline_token
        - redhat_username
        - redhat_password
      delegate_to: localhost

  tasks:
    - name: Include common mesh worker node tasks
      vars:
        receptor_packages:
          - receptor
          - receptorctl
          - podman
          - crun
          - ansible-runner
          - libcgroup-tools
          - subscription-manager-rhsm-certificates
          - rsync
          - git
          - ansible
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/30_mesh_node.yml"

    - name: Include common user tasks
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/5_configure_users.yml"

    - name: Include common image cleanup tasks
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/common/10_image_cleanup.yml"
