#!/usr/bin/env python3

import subprocess
import yaml
from shlex import quote
import os

os.environ["ANSIBLE_VAULT_PASSWORD_FILE"] = ".lightspeed-101_ansible_vault_password"
setup_scripts_path="/opt/setup-scripts/lightspeed-101/"

# Change working dir
os.chdir(setup_scripts_path)
# Load extra_vars.yml
extra_vars_file = open("/opt/setup-scripts/lightspeed-101/vars/track_vars.yml")
extra_vars = yaml.load(extra_vars_file, yaml.loader.FullLoader)

# Check monitoring
check_monitoring = subprocess.run(["ansible-navigator", "run",
                                setup_scripts_path + "lightspeed-101-lab_setup.yml", 
                                "-e", "check_mode=true",
                                "--tags", "check-monitoring-cockpit",
                                "--mode", "stdout"])

if check_monitoring.returncode > 0:
    print ("FAIL: Cockpit application is not running. Please make sure you've updated the " + quote(extra_vars["monitoring"]["playbook_names"][0]) + " Playbook and ran it using 'ansible-navigator', or committed and pushed it to the repository and ran the " + quote(extra_vars["monitoring"]["jt_names"][0]) + " Job Template in controller." )
    exit(1)