---
# config vars
download_url: https://github.com/craig-br/instruqt/branches/devops-controller-track/images/ansible/setup-scripts/devops-controller
ansible_python_interpreter: /usr/bin/python3
student_user: student
student_password: learn_ansible
host_key_checking: false
custom_facts_dir: "/etc/ansible/facts.d"
custom_facts_file: custom_facts.fact
admin_username: admin
admin_password: ansible123!
git_repo: http://gitea:3000/{{ student_user }}/acme_corp.git
jenkins_jobs:
  - name: ACMECorp
    template_file: /tmp/setup-scripts/devops-controller/files/acme.xml
  - name: PollRepo
    template_file: /tmp/setup-scripts/devops-controller/files/poll.xml

# Controller objects
lab_credential_name: "ACME Corp Machine Credential"
lab_organization: "ACME Corp"
lab_project_name: "ACME Corp Repo"
lab_inventories:
  - name: "ACME Corp DC"
    description: "ACME Corp DC"
lab_hosts:
  - lab_host_name: "web1.acme.example.com"
    lab_host_inventory: "ACME Corp DC"
    lab_host_vars:
      ansible_host: controller 
      ansible_python_interpreter: /usr/bin/python3
      ansible_host_key_checking: false
  - lab_host_name: "jenkins.acme.example.com"
    lab_host_inventory: "ACME Corp DC"
    lab_host_vars:
      ansible_host: jenkins 
      ansible_python_interpreter: /usr/bin/python3
      ansible_host_key_checking: false
  - lab_host_name: "repo.acme.example.com"
    lab_host_inventory: "ACME Corp DC"
    lab_host_vars:
      ansible_host: jenkins 
      ansible_python_interpreter: /usr/bin/python3
      ansible_host_key_checking: false