version: "2"
virtualmachines:
- name: controller
  image: red-hat-mbu/automation-controller
  environment:
    TERM: xterm
  machine_type: n1-standard-4
- name: node1
  image: red-hat-mbu/ansible
  shell: /bin/su - rhel -s /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
