#!/bin/bash

export ADMIN_CONTROLLER_USERNAME=`agent variable get ADMIN_CONTROLLER_USERNAME`
export ADMIN_CONTROLLER_PASSWORD=`agent variable get ADMIN_CONTROLLER_PASSWORD`

ansible-playbook -e "job_template_name='2 - Attach problem (problem-attach.yml)'" /tmp/check-jt-run.yml --tags solve