---
- name: Manage Google Compute Images
  block:
    - name: Manage GCP Images - {{ gcp_resources_images_state }}
      google.cloud.gcp_compute_image:
        auth_kind: "{{ __manage_images_async_item.auth_kind | default(omit) }}"
        description: "{{ __manage_images_async_item.description | default(omit) }}"
        disk_size_gb: "{{ __manage_images_async_item.disk_size_gb | default(omit) }}"
        family: "{{ __manage_images_async_item.family | default(omit) }}"
        guest_os_features: "{{ __manage_images_async_item.guest_os_features | default(omit) }}"
        image_encryption_key: "{{ __manage_images_async_item.image_encryption_key | default(omit) }}"
        licenses: "{{ __manage_images_async_item.licenses | default(omit) }}"
        name: "{{ __manage_images_async_item.name }}"
        project: "{{ gcp_project | default(omit) }}"
        raw_disk: "{{ __manage_images_async_item.raw_disk | default(omit) }}"
        source_disk: "{{ __manage_images_async_item.source_disk | default(omit) }}"
        source_disk_encryption_key: "{{ __manage_images_async_item.source_disk_encryption_key | default(omit) }}"
        source_disk_id: "{{ __manage_images_async_item.source_disk_id | default(omit) }}"
        source_image: "{{ __manage_images_async_item.source_image | default(omit) }}"
        source_snapshot: "{{ __manage_images_async_item.source_snapshot | default(omit) }}"
        state: "{{ __manage_images_async_item.state | default(gcp_resources_images_state) }}"
        labels: "{{ __manage_images_async_item.labels | default(omit) }}"
        source_type: "{{ __manage_images_async_item.source_type | default(omit) }}"
        service_account_contents: "{{ __manage_images_async_item.service_account_contents | default(omit) }}"
        service_account_file: "{{ __manage_images_async_item.service_account_file | default(omit) }}"
        service_account_email: "{{ __manage_images_async_item.service_account_email | default(omit) }}"
        access_token: "{{ __manage_images_async_item.access_token | default(omit) }}"
        scopes: "{{ __manage_images_async_item.scopes | default(omit) }}"
      loop: "{{ gcp_resources_images }}"
      loop_control:
        loop_var: __manage_images_async_item
        label: "{{ __manage_images_async_item.name }}"
      async: 1000
      poll: 0
      register: __manage_images_async
      changed_when: not __manage_images_async.changed

    - name: Manage GCP Images | Async
      ansible.builtin.async_status:
        jid: "{{ __manage_images_async_result_item.ansible_job_id }}"
      retries: 180
      delay: 1
      loop: "{{ __manage_images_async.results }}"
      loop_control:
        loop_var: __manage_images_async_result_item
        label: "{{ __manage_images_async_result_item.__manage_images_async_item.name }}"
      until: __manage_images_async_result.finished
      register: __manage_images_async_result
      when: __manage_images_async_result_item.ansible_job_id is defined
  rescue:
    - name: Print error message
      ansible.builtin.fail:
        msg: |
          "Rescue - Unable to remove gcloud images."
          "{{ __manage_images_async_result }}"
      notify:
        - remove instances
