#!/usr/bin/env python3

import subprocess
import yaml
from shlex import quote
import os

os.environ["ANSIBLE_VAULT_PASSWORD_FILE"] = ".lightspeed-101_ansible_vault_password"
setup_scripts_path="/opt/setup-scripts/lightspeed-101/setup/"

# Change working dir
os.chdir(setup_scripts_path)
# Load extra_vars.yml
extra_vars_file = open("/opt/setup-scripts/lightspeed-101/setup/vars/track_vars.yml")
parsed_extra_vars_file = yaml.load(extra_vars_file, yaml.loader.FullLoader)

# Check podman container
check_podman_app = subprocess.run(["ansible-navigator", "run",
                                setup_scripts_path + "lightspeed-101-lab_setup.yml", 
                                "--tags", "check-keywords-app",
                                "--mode", "stdout"])
if check_podman_app.returncode > 0:
    print ( "FAIL: Please make sure you've updated the 'deploy_app.yml' Playbook, committed and pushed it to the repository, and ran the 'Deploy ACME Corp app' Job Template in controller." )
    exit(1)

# Check monitor app
check_monitor_app = subprocess.run(["ansible-navigator", "run",
                                setup_scripts_path + "lightspeed-101-lab_setup.yml", 
                                "--tags", "check-keywords-monitor",
                                "-e", "check_mode=true",
                                "--mode", "stdout"])
if check_monitor_app.returncode > 0:
    print ( "FAIL: Please make sure you've updated the 'deploy_monitoring.yml' Playbook, committed and pushed it to the repository, and ran the 'Deploy ACME Corp app' Job Template in controller." )
    exit(1)
