#!/usr/bin/env python3

import subprocess
import yaml
from shlex import quote
import os

os.environ["ANSIBLE_VAULT_PASSWORD_FILE"] = ".lightspeed-101_ansible_vault_password"
setup_scripts_path="/opt/setup-scripts/lightspeed-101/setup/"

# Change working dir
os.chdir(setup_scripts_path)
# Load extra_vars.yml
extra_vars_file = open("/opt/setup-scripts/lightspeed-101/setup/vars/track_vars.yml")
parsed_extra_vars_file = yaml.load(extra_vars_file, yaml.loader.FullLoader)

# Load playbooks, sync project and configure firewall
setup_generate_playbooks = subprocess.run(["ansible-navigator", "run",
                                setup_scripts_path + "lightspeed-101-lab_setup.yml", 
                                "-e", "content_list=keywords",
                                "-e", "state='disabled'",
                                "-e", "check_mode=false",
                                "--tags", "setup-keywords-playbook,setup-keywords-sync,setup-keywords-jt,setup-keywords-container,setup-keywords-fw",
                                "--mode", "stdout"])

if setup_generate_playbooks.returncode > 0:
    print ( "Keywords - Did not complete setup script" )

iptables_flush = subprocess.run(["iptables", "-t", "nat", "-F"])
firewall_reload =subprocess.run(["firewall-cmd", "--reload"])