#!/usr/bin/env python3

import subprocess
import yaml
from shlex import quote
import os

os.environ["ANSIBLE_VAULT_PASSWORD_FILE"] = ".lightspeed-101_ansible_vault_password"
setup_scripts_path="/opt/setup-scripts/lightspeed-101/setup/"

# Change working dir
os.chdir(setup_scripts_path)
# Load extra_vars.yml
extra_vars_file = open("/opt/setup-scripts/lightspeed-101/setup/vars/track_vars.yml")
parsed_extra_vars_file = yaml.load(extra_vars_file, yaml.loader.FullLoader)

# Check firewall ports
check_external_fw = subprocess.run(["ansible-navigator", "run",
                                setup_scripts_path + "lightspeed-101-lab_setup.yml", 
                                "--tags", "check-external-content-fw",
                                "-e", "check_mode=true",
                                "-e", "state='enabled'",
                                "--mode", "stdout"])

if check_external_fw.returncode > 0:
    print ("FAIL: The Monitoring app firewall ports are blocked. Please make sure you've created the Playbook, commited and pushed the code to the repository, and run the 'Configure firewall' Job Template in controller.")
    exit(1)
