#!/bin/bash
set -e

INVENTORY="lab-inventory"
PROJECT="Apache playbooks"
PROJECT2="Additional playbooks"
TEMPLATE="Install Apache"
TEMPLATE2="Set motd"
TEMPLATE3="Extended services"
WORKFLOW="Your first workflow"
CREDENTIALS="lab-credentials"
HOSTS=(node1 node2)
GROUP="web"

#Ansible settings
export ANSIBLE_STDOUT_CALLBACK="community.general.yaml"
export CONTROLLER_HOST=localhost
export CONTROLLER_USERNAME=admin
export CONTROLLER_PASSWORD='ansible123!'
export CONTROLLER_VERIFY_SSL=false

# Playbook run command
CMD="/bin/ansible-playbook /tmp/controller-101-setup.yml"

# Check $CREDENTIALS exists.
if [ !$CMD --tags=check-credentials -vv ]; then
 echo "FAIL: ${CREDENTIALS} template not found. Remember it's case-sensitive! Please try again."
 exit 1
fi
