#!/bin/bash
set -euxo pipefail

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

cp -a /root/.ssh/id_rsa* /root/.ssh/authorized_keys /home/rhel/.ssh
chown -R rhel:rhel /home/rhel/.ssh

# Update containers
/bin/podman auto-update

# Testing Get instruqt lab content
# rm -rf /opt/setup-scripts/lightspeed-101
# /usr/bin/aws s3 sync --no-sign-request s3://tmm-instruqt-content.demoredhat.com.private/lightspeed-101 /opt/setup-scripts/lightspeed-101

cd /opt/setup-scripts/lightspeed-101/
ln ~root/.lightspeed-101_ansible_vault_password .lightspeed-101_ansible_vault_password
chmod 600 ~root/.lightspeed-101_ansible_vault_password
export ANSIBLE_VAULT_PASSWORD_FILE=.lightspeed-101_ansible_vault_password

# Fix DNS so ansible-navigator resolves lightspeed-101-controller to FQDN 10.x.x.x. IP address.
sed -i '/127\.0\.0\.1.*lightspeed-101-controller/d' /etc/hosts
