version: "3"
virtualmachines:
- name: node2
  image: red-hat-mbu/ansible
  shell: /bin/su - rhel -s /bin/bash
  machine_type: n1-standard-1
- name: node1
  image: red-hat-mbu/ansible
  shell: /bin/su - rhel -s /bin/bash
  machine_type: n1-standard-1
- name: controller
  image: red-hat-mbu/automation-controller
  shell: /bin/su - rhel -s /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-4
  allow_external_ingress:
  - http
  - https
secrets:
- name: ADMIN_CONTROLLER_PASSWORD
- name: ADMIN_CONTROLLER_USERNAME
- name: VAULT_PASSWORD
- name: ANSIBLE_TMM_CONTROLLER_TOKEN
