version: "3"
virtualmachines:
  - name: node2
    image: red-hat-mbu/ansible
    shell: /bin/su - rhel -s /bin/bash
    machine_type: n1-standard-1
  - name: node1
    image: red-hat-mbu/ansible
    shell: /bin/su - rhel -s /bin/bash
    machine_type: n1-standard-1
  - name: controller
    image: red-hat-mbu/automation-controller
    shell: /bin/su - rhel -s /bin/bash
    environment:
      TERM: xterm
    machine_type: n1-standard-4
