---
- name: EC2 Cloud Operations
  hosts: localhost
  connection: local
  gather_facts: false

  module_defaults:
    group/aws:
      region: us-east-1

  vars:
    ec2_instance:
      name: instance-lightspeed-01
      key_name: lightspeed-keypair
      image_id: ami-016eb5d644c333ccb # RHEL 9 us-east-1
      network:
        assign_public_ip: true
      tags:
        function: demo-lightspeed
      security_group: secgroup-lightspeed
      wait: true

  tasks:
############################################## INSTRUCTIONS TASK 1 and 2 ##############################################
# Press "ENTER" at the end of the multi-task prompt line just after this instructions block. DO NOT UNCOMMENT THE LINE.
# Press "TAB" to accept suggestion.
# Note - The suggestion used the Fully Qualified Collection Name (FQCN).
# Note - The first task used the correct AWS tag "tag:Name" in the filter.
# Note - The second task used the correct variable created in the previous task.
#######################################################################################################################

    # Gather info from subnet called subnet-lightspeed & create vpc_subnet_id var
    - name: Gather info from subnet called subnet-lightspeed
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          tag:Name: subnet-lightspeed
      register: subnet_info

    - name: Create vpc_subnet_id var
      ansible.builtin.set_fact:
        vpc_subnet_id: "{{ subnet_info.subnets[0].id }}"

################################################# INSTRUCTIONS TASK 3 #################################################
# Uncomment the line just after this instructions block and Press "ENTER" at the end.
# Press "TAB" to accept suggestion.
# Note - The suggestion used the "ec2_instance" variable declared in the "vars:" section.
#######################################################################################################################

    - name: Provision t3.small instance using ec2_instance var
      amazon.aws.ec2_instance:
        name: "{{ ec2_instance.name }}"
        key_name: "{{ ec2_instance.key_name }}"
        image_id: "{{ ec2_instance.image_id }}"
        network: "{{ ec2_instance.network }}"
        security_group: "{{ ec2_instance.security_group }}"
        wait: "{{ ec2_instance.wait }}"
        instance_type: t3.small
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        tags: "{{ ec2_instance.tags }}"
      register: ec2_instance_info

############################################## INSTRUCTIONS TASK 4 and 5 ##############################################
# Press "ENTER" at the end of the multi-task prompt line just after this instructions block. DO NOT UNCOMMENT THE LINE.
# Press "TAB" to accept suggestion.
# Note - The suggestion used the correct variable from the previous task.
# Note - The second task used the "public_ip_address" variable based on the previous task.
# First task note - The suggestion used the correct variable from the previous task and integrated "retries".
# Second task note - The suggestion used the "public_ip_address" variable based on the previous task.
#######################################################################################################################

    # Create var from public_ip_address with retry & print it out
    - name: Create var from public_ip_address with retry
      ansible.builtin.set_fact:
        public_ip_address: "{{ ec2_instance_info.instances[0].public_ip_address }}"
      retries: 10
      delay: 10
      until: public_ip_address is defined

    - name: Print it out
      ansible.builtin.debug:
        msg: "{{ public_ip_address }}"
