#!/bin/bash
USER=rhel

# calls a job template on ansible.demoredhat.com to create a new user on ansible.service-now.com
curl -k -X POST https://ansible.demoredhat.com/api/v2/job_templates/88/launch/ -H "Content-Type: application/json"  -H "Authorization: Bearer 8tGvwVFVGsKgYStxueyt5LNUh36T5I" -d "{\"extra_vars\": {\"random_user\":\"$INSTRUQT_PARTICIPANT_ID\",\"cleanup\":false,\"demo_password\":\"$INSTRUQT_PARTICIPANT_ID\"}}"

# creates the correct credential for servicenow on Controller
su - rhel -c 'ansible-galaxy collection install awx.awx'

# create project directory
su - rhel -c 'mkdir /home/rhel/servicenow_project'

# creates a playbook to add a credential to Controller
tee -a /home/rhel/create-credential.yml << EOF
---
- name: Creates SNOW cred in Controller

  hosts: localhost
  connection: local

  collections:
    - awx.awx
 
  tasks:
  - name: add snow credential
    awx.awx.credential:
      name: 'servicenow credential'
      organization: Default
      credential_type: servicenow.itsm
      controller_host: "https://{{ ansible_host }}"
      controller_username: admin
      controller_password: ansible123!
      validate_certs: false
      inputs:
        SN_USERNAME: "{{ lookup('env', 'INSTRUQT_PARTICIPANT_ID') }}"
        SN_PASSWORD: "{{ lookup('env', 'INSTRUQT_PARTICIPANT_ID') }}"
        SN_HOST: https://ansible.service-now.com

EOF

# chown above file
sudo chown rhel:rhel /home/rhel/create-credential.yml

# execute above playbook
su - rhel -c 'ansible-playbook /home/rhel/create-credential.yml'

# populate readme file with environment credentials
su - rhel -c 'tee -a /home/rhel/servicenow_project/readme.md << EOF
# Environment credentials

## Automation Controller
- username: admin
- password: ansible123!

## ServiceNow
- username: $(echo $INSTRUQT_PARTICIPANT_ID)
- password: $(echo $INSTRUQT_PARTICIPANT_ID)

EOF'

# allow awx and all others access to that home director
chmod a+x /home/rhel/

# symlink project directory in home dir so it can be picked up by controller
su - awx -c 'ln -s /home/rhel/servicenow_project/ /var/lib/awx/projects/'

# create playbook for project import
su - rhel -c 'tee -a /home/rhel/project-create.yml << EOF
---
- name: Configure local project 
  hosts: localhost
  connection: local
  collections:
    - awx.awx

  tasks:

  - name: Add project
    awx.awx.project:
      name: "ServiceNow"
      description: "Project containing users ServiceNow playbooks"
      organization: Default
      state: present
      scm_type: manual
      local_path: servicenow_project
      controller_host: "https://localhost"
      controller_username: admin
      controller_password: ansible123!
      validate_certs: false

EOF'

# execute playbook
su - rhel -c 'ansible-playbook /home/rhel/project-create.yml'

# Remove demo job template
su - rhel -c 'tee /home/rhel/template-destroy.yml << EOF
---
- name: Destroy job template
  hosts: localhost
  connection: local
  collections:
    - awx.awx

  tasks:

    - name: Remove demo job template
      job_template:
        name: "Demo Job Template"
        job_type: "run"
        organization: "Default"
        inventory: "Demo Inventory"
        # project: "ServiceNow"
        # playbook: "incident-create.yml"
        # credentials:
        #   - "servicenow credential"
        state: "absent"
        controller_host: "https://localhost"
        controller_username: admin
        controller_password: ansible123!
        validate_certs: false

EOF'

# Execute above playbook
su - rhel -c 'ansible-playbook /home/rhel/template-destroy.yml'
