#!/bin/bash
set -e

INVENTORY="Lab-Inventory"
PROJECT="Apache playbooks"
PROJECT2="Additional playbooks"
TEMPLATE_APACHE="Install Apache"
TEMPLATE2="Set motd"
TEMPLATE3="Extended services"
WORKFLOW="Your first workflow"
HOSTS=(node1 node2)
GROUP="web"

#Ansible settings
export ANSIBLE_STDOUT_CALLBACK="community.general.yaml"
export CONTROLLER_HOST=localhost
export CONTROLLER_USERNAME=admin
export CONTROLLER_PASSWORD='ansible123!'
export CONTROLLER_VERIFY_SSL=false

# Playbook run command
CMD="/bin/ansible-playbook /tmp/controller-101-setup.yml"

## Check $TEMPLATE_APACHE exists.
if ! $CMD --tags=check-template -vv ; then
 echo "FAIL: ${TEMPLATE_APACHE} template not found or wrong! Review tasks and please try again."
 exit 1
fi


CMDAPA="/bin/ansible-playbook /tmp/setup-scripts/getting-started-controller/getting-started-controller-setup.yml  --tags=check-template -vv"

## Check $TEMPLATE_APACHE exists.
#if [ !$CMDAPA ]; then
# echo "FAIL: ${TEMPLATE_APACHE} template not found or wrong! Review tasks and please try again."
# exit 1
#fi

