#!/usr/bin/python3

import subprocess, os

setup_scripts_path="/opt/setup-scripts/getting-started-mesh/"
os.environ["ANSIBLE_CONFIG"] = setup_scripts_path+"ansible.cfg"

# Solve multi-site
mesh_multi_site_solve = subprocess.run(["ansible-playbook", setup_scripts_path+"getting-started-mesh-setup.yml",
                                        "--tags", "multi-site-solve"])