#!/bin/bash

# make challenge dir
su - rhel -c 'mkdir /home/rhel/challenge-2'

# Create a playbook for the user to execute which will create a SN incident
tee /home/rhel/servicenow_project/problem-attach.yml << EOF
---
- name: Automate SNOW 
  hosts: localhost
  connection: local
  collections:
    - servicenow.itsm
    
  vars:
    demo_username: "{{ lookup('env', 'SN_USERNAME') }}"
    incident_list: []

  tasks:

    - name: find user created incidents
      servicenow.itsm.incident_info:
        query:
          - sys_created_by: LIKE {{ demo_username }}
            active: = true
      register: incidents

    - name: query incident number and creation time 
      set_fact:
        incident_list: '{{ incident_list + [{"number": item.number, "opened_at": item.opened_at}] }}'
      loop: "{{ incidents.records }}"
      when: incidents

    - name: Create a problem from incident
      servicenow.itsm.problem:
        short_description: "The website is completely down!!!!"
        description: "{{ lookup('env', 'SN_USERNAME') }} created a new problem"
      register: problem

    - name: Assign a problem to a user for assessment
      servicenow.itsm.problem:
        number: "{{ problem.record.number }}"
        state: assess
        assigned_to: "{{ lookup('env', 'SN_USERNAME') }}"

    - name: Update incident status now that problem has been created
      servicenow.itsm.incident:
        number: "{{ item.number }}"
        state: in_progress
        other:
          problem_id: "{{ problem.record.number }}"
      loop: "{{ incident_list }}"

    - debug:
        msg: "A new problem has been created {{ problem.record.number }}"

EOF

# chown above file
sudo chown rhel:rhel /home/rhel/servicenow_project/problem-attach.yml

# Write a new playbook to create a template from above playbook
tee /home/rhel/challenge-2/template-create.yml << EOF
---
- name: Create job template for problem-attach
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx

  tasks:

    - name: Post create-incident job template
      job_template:
        name: "2 - Attach problem (problem-attach.yml)"
        job_type: "run"
        organization: "Default"
        inventory: "Demo Inventory"
        project: "ServiceNow"
        playbook: "problem-attach.yml"
        execution_environment: "ServiceNow EE"
        credentials:
          - "servicenow credential"
        state: "present"
        ask_variables_on_launch: false
        extra_vars:
          mapping:
            problem:
              state:
                1: "open"
                2: "known_error"
                3: "pending_change"
                4: "closed_resolved"
                5: "closed"
              problem_state:
                1: "open"
                2: "known_error"
                3: "pending_change"
                4: "closed_resolved"
                5: "closed"
        controller_host: "https://localhost"
        controller_username: admin
        controller_password: ansible123!
        validate_certs: false

EOF

# chown above file
sudo chown rhel:rhel /home/rhel/challenge-2/template-create.yml

# Execute above playbook
su - rhel -c 'ansible-playbook /home/rhel/challenge-2/template-create.yml'

# Grant student account access to challenge job template 
tee /home/rhel/challenge-2/role-update.yml << EOF
---
- name: Create job template for create-incident
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx

  tasks:

    - name: Post create-incident job template
      role:
        user: student
        role: execute
        job_templates:
          - "1 - Create incident (incident-create.yml)"
          - "2 - Attach problem (problem-attach.yml)"
        controller_username: admin
        controller_password: ansible123!
        validate_certs: false

EOF

# chown above file
sudo chown rhel:rhel /home/rhel/challenge-2/role-update.yml

# Execute above playbook
su - rhel -c 'ansible-playbook /home/rhel/challenge-2/role-update.yml'
