---
all:
  children:
    nodes:
      hosts:
        lightspeed-101-rhel-node1:
          ansible_become_password: "{{ vault_admin_password }}"
    automationcontroller:
      hosts:
        controller.acme.example.com:
          ansible_host: lightspeed-101-controller
  vars:
    ansible_ssh_private_key_file: ~/.ssh/instruqt_lab
    ansible_user: "{{ vault_admin_username }}"
    ansible_password: "{{ vault_admin_password }}"

    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=60s'
    ansible_ssh_pipelining: true
    ansible_host_key_checking: false
