#!/bin/bash

echo "devops ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/devops

yum install -y yum-utils

yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

yum install -y docker-ce docker-ce-cli containerd.io

systemctl start docker