#!/usr/bin/python3

import subprocess, os

instance_groups = {
   "'Johannesburg data center'": {
      'hosts':
         "'jhb-exec'"
   },
   "'Raleigh data center'": {
      'hosts':
         "'raleigh-controller'"
   }
}
setup_scripts_path="/opt/setup-scripts/getting-started-mesh/"
os.environ["ANSIBLE_CONFIG"] = setup_scripts_path+"ansible.cfg"

# Check if instance group exists and correct instance is assigned
for key, value in instance_groups.items():
    instance_group_output = subprocess.run(["ansible-playbook", setup_scripts_path+"getting-started-mesh-setup.yml",
                                             "-e", "lab_instance_group_name="+key,
                                             "--tags", "mesh-instance-groups-check"])
    if instance_group_output.returncode > 0:
        print ( "FAIL: The " + key + " instance group was not found. Please try again and remember it's case-sensitive!" )
        exit(1)
    for hosts in instance_groups[key].values():
        instance_group_instances_output = subprocess.run(["ansible-playbook", setup_scripts_path+"getting-started-mesh-setup.yml", 
                                                         "-e", "lab_instance_group_name="+key,
                                                         "-e", "lab_instance_group_instance_name="+hosts,
                                                         "--tags", "mesh-instance-groups-instances-check"])
        if instance_group_instances_output.returncode > 0:
            print ( "FAIL: The " + hosts + " instance is missing from the " + key + " instance group. Please try again and remember it's case-sensitive!" )
            exit(1)