#!/bin/bash
set -euxo pipefail

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

#Create setup-scripts dir
# mkdir -p /tmp/setup-scripts/devops-controller

# Get instruqt lab content
# /usr/bin/svn export https://github.com/craig-br/instruqt/branches/devops-controller-track/images/ansible/setup-scripts/devops-controller /tmp/setup-scripts/devops-controller --force

# Run Jenkins config
# echo "Starting Jenkins config"
# /usr/bin/ansible-playbook /tmp/setup-scripts/devops-controller/setup-devops-controller.yml -e @/tmp/setup-scripts/devops-controller/track_vars.yml  -i /tmp/setup-scripts/devops-controller/inventory.ini --tags jenkins-config --skip-tags always -v
# Setup rhel user
# touch /etc/sudoers.d/rhel_sudoers
# echo "%rhel ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/rhel_sudoers
# cp -a /root/.ssh/* /home/rhel/.ssh/.
# chown -R rhel:rhel /home/rhel/.ssh

# while [[ "$(curl --insecure --output /dev/null --write-out ''%{http_code}'' https://controller)" != 200 ]]; do
#   sleep 3
#   printf 'Waiting for controller bootstrap to complete'
# done

# timeout 120 bash -c 'while ! ssh rhel@controller [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
#   echo "Waiting for controller to complete bootstrap"
#   sleep 3
# done' || false

# /usr/bin/svn export https://github.com/craig-br/instruqt/branches/devops-controller-track/images/ansible/setup-scripts/devops-controller /tmp/setup-scripts/devops-controller
# /bin/su - jenkins
# timeout 20 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' jenkins:8080)" != 200 ]]
# do
#     echo " Waiting for Jenkins to start"
#     sleep 3;
# done' || false

# /usr/bin/curl http://jenkins:8080/jnlpJars/jenkins-cli.jar --output jenkins-cli.jar

# /opt/java/openjdk/bin/java -jar jenkins-cli.jar -s http://jenkins:8080 -auth "admin":"learn_ansible" create-job ACMECorp < /tmp/setup-scripts/devops-controller/files/acme.xml
# /opt/java/openjdk/bin/java -jar jenkins-cli.jar -s http://jenkins:8080 -auth "admin":"learn_ansible" create-job PollRepo < /tmp/setup-scripts/devops-controller/files/poll.xml


