#!/bin/bash

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

/bin/su - git -c '/usr/local/bin/gitea admin user create --admin --username student --password learn_ansible --email root@localhost'

