#!/bin/bash

# Set the target directory and file
target_directory="/home/rhel/ansible-files"
target_file="${target_directory}/apache.yml"

# Provide the apache.yml content
read -r -d '' desired_content << 'EOF'
---
- name: Apache server installed
  hosts: node1
  become: true
  tasks:
  - name: latest Apache version installed
    ansible.builtin.package:
      name: httpd
      state: latest
EOF

# Write the desired content to the 'apache.yml' file
echo "$desired_content" > "$target_file"
