#!/bin/bash
## check file

USER=rhel

# Set the target directory and file
target_directory="/home/rhel/ansible-files"
target_file="${target_directory}/system_setup.yml"
solve_file="/tmp/first-101/solve_13_system_setup_webhosts.yml"
check_file="/tmp/system_setup_check_web.yml"

# Make sure solvers exist
/usr/bin/git clone https://github.com/leogallego/instruqt-wyfp-2024-solve.git /tmp/first-101

# Copy solved playbook
#cp $solve_file $target_file
#chown $USER:$USER $target_file 


# Check if the target_file file exists
if [ -f "$target_file" ]; then
    # Read the content of the target_file file and solve_file
    file_content=$(cat "$target_file")
    solve_content=$(cat "$solve_file")

    # Compare the content of the target_file file with the expected content
    if [ "$file_content" != "$solve_content" ]; then
        fail-message "Challenge 1.3 - The 'system_setup.yml' file does not have the proper content. Please check the file and try again."
    fi
else
    fail-message "Challenge 1.3 - The 'system_setup.yml' file does not exist in the specified directory."
fi


su - $USER -c 'cat >/tmp/system_setup_check_web.yml <<EOL
---
- name: System Configuration Checks
  hosts: web
  become: true
  tasks:
    - name: Check user existence
      ansible.builtin.command:
        cmd: id myuser
      register: user_check
 
    - name: Report user status
      ansible.builtin.debug:
        msg: "User 'myuser' exists."
      when: user_check.rc == 0

EOL
cat /tmp/system_setup_check_web.yml'

# Check if the new user exists on the remote host
cd $target_directory
CMD='ansible-navigator run /tmp/system_setup_check_web.yml -m stdout'

# Check user exists.
if ! $CMD -vv; then
 echo "Challenge 1.2 - FAIL: myuser does not exist. Something is wrong."
 exit 1
fi

# Run solve playbook
#su - $USER -c 'ansible-navigator run /tmp/first-101/solve_11_system_setup.yml -m stdout'
#cd $target_directory
#ansible-navigator run $target_file -m stdout --check