---
- name: solve challenge 3
  hosts: localhost
  gather_facts: false
  become: true
  tasks:

    - name: Create network backup job template
      awx.awx.job_template:
        name: "Network Automation - Backup"
        job_type: "run"
        organization: "Default"
        inventory: Network Inventory
        project: "Network Toolkit"
        playbook: "playbooks/network_backup.yml"
        credentials:
          - "Network Credential"
          - "AAP controller credential"
        state: "present"
        extra_vars:
          restore_inventory: "Network Inventory"
          restore_project: "Network Toolkit"
          restores_playbook: "playbooks/network_restore.yml"
          restore_credential: "Network Credential"
        controller_config_file: "{{ playbook_dir }}/../controller.cfg"

    - name: Launch Network Automation - Backup
      awx.awx.job_launch:
        job_template: "Network Automation - Backup"
