#!/bin/bash

# Set the working directory
cd /home/rhel/ansible-files

# Define the desired hosts file content
desired_content=$'[web]\nnode1\nnode2'

# Write the desired content to the 'hosts' file
echo -e "$desired_content" > hosts
