#!/usr/bin/env python3

import subprocess
import yaml
from shlex import quote
import os

os.environ["ANSIBLE_VAULT_PASSWORD_FILE"] = ".lightspeed-101_ansible_vault_password"
setup_scripts_path="/opt/setup-scripts/lightspeed-101/setup/"

# Change working dir
os.chdir(setup_scripts_path)
# Load extra_vars.yml
extra_vars_file = open("/opt/setup-scripts/lightspeed-101/setup/vars/track_vars.yml")
parsed_extra_vars_file = yaml.load(extra_vars_file, yaml.loader.FullLoader)

# Create and run workflow job template
check_workflow_created = subprocess.run(["ansible-navigator", "run",
                                setup_scripts_path + "lightspeed-101-lab_setup.yml", 
                                "--tags", "check-workflow-create-wjt",
                                "-e", "jt_name=" + quote(parsed_extra_vars_file.get("lab").get("workflow_name")),
                                "-e", "check_mode=true",
                                "--mode", "stdout"])

if check_workflow_created.returncode > 0:
    print ( "FAIL: The " + quote(parsed_extra_vars_file.get("lab").get("workflow_name")) + " Workflow not found. Please make sure you've created it." )
    exit(1)

check_workflow_schema = subprocess.run(["ansible-navigator", "run",
                                setup_scripts_path + "lightspeed-101-lab_setup.yml", 
                                "--tags", "check-workflow-schema",
                                "-e", "jt_name=" + quote(parsed_extra_vars_file.get("lab").get("workflow_name")),
                                "-e", "check_mode=true",
                                "--mode", "stdout"])

if check_workflow_schema.returncode > 0:
    print ( "FAIL: The " + quote(parsed_extra_vars_file.get("lab").get("workflow_name")) + " Workflow exists, but doesn't have the corrrect configuration. Please try again or launch the 'Solve - Create workflow' Job Template for help." )
    exit(1)
