# Perform common image cleanup tasks
- name: Gather current standard users
  ansible.builtin.shell: >
    cut -d: -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d: -f1
  changed_when: false
  register: _standard_users

- name: Remove all normal users except rhel,awx,pulp and student
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: true
  loop: "{{ _standard_users.stdout_lines }}"
  when:
    - item != "rhel"
    - item != "awx"
    - item != "pulp"
    - item != "student"

- name: disable dnf automatic services
  ansible.builtin.service:
    name: "dnf-automatic.timer"
    state: stopped

- name: automatic.conf disable downloads
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: '^download_updates'
    line: download_updates = no

- name: automatic.conf disable updates
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: '^apply_updates'
    line: apply_updates = no

- name: Enable selected RHUI repos
  ansible.builtin.copy:
    src: ../files/rh-cloud.repo
    dest: /etc/yum.repos.d/rh-cloud.repo
    owner: root
    group: root
    mode: '644'

- name: Update dnf cache
  ansible.builtin.command: dnf -y makecache

- name: remove AAP repo
  ansible.builtin.yum_repository:
    name: aap_installer
    state: absent

- name: remove AAP install dir
  ansible.builtin.file:
    path: "{{ aap_dir }}"
    state: absent
  ignore_errors: true

- name: Remove bash history file
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.bash_history"
    state: absent

- name: Clear bash history
  ansible.builtin.shell: history -c; history -w
