# Common user tasks
- name: Configure user 'rhel'
  ansible.builtin.user:
    name: rhel
    shell: /bin/bash
    password: "{{ admin_password | password_hash('sha512', 'mysecretsalt') }}"
    groups: wheel
    append: true

- name: Enable sshd password auth
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    mode: "0644"
    regexp: '^PasswordAuthentication'
    line: >-
      PasswordAuthentication yes

- name: Configure sudoers for wheel group
  community.general.sudoers:
    name: wheel_sudooers
    state: present
    commands:
      - ALL
    nopassword: true
    group: wheel

- name: Create receptor group
  ansible.builtin.group:
    name: receptor
    state: present

- name: Create awx user and add to receptor group
  ansible.builtin.user:
    name: awx
    groups: receptor
    append: true
    home: /var/lib/awx
    shell: /bin/bash

- name: Create restricted user - {{ student_username }}
  ansible.builtin.user:
    name: "{{ student_username }}"
    shell: /bin/bash
    groups: users
    password: "{{ student_password | password_hash('sha512', '98263y4krwf7400') }}"

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
