# Configure rhel user
- name: Configure user 'rhel'
  ansible.builtin.user:
    name: rhel
    shell: /bin/bash
    password: "{{ admin_password | password_hash('sha512', 'mysecretsalt') }}"
    groups: wheel
    append: true

- name: enable sshd password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication'
    line: >-
      PasswordAuthentication yes

- name: Setup sudo for rhel user
  ansible.builtin.copy:
    content: "%rhel ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/rhel_sudoers"

- name: create receptor group
  ansible.builtin.group:
    name: receptor
    state: present

- name: Create awx user and add to receptor group
  ansible.builtin.user:
    name: awx
    groups: receptor
    append: true
    home: /var/lib/awx
    shell: /bin/bash

- name: Create restricted user - {{ student_user }}
  ansible.builtin.user:
    name: "{{ student_user }}"
    shell: /bin/bash
    password: "{{ student_password | password_hash('sha512', '98263y4krwf7400') }}"
  tags:
    - controller-install

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
