version: "3"
containers:
- name: azurecloudclient
  image: gcr.io/instruqt/rhaap-on-ms-azure-cloud-client
  ports:
  - 80
  memory: 256
virtualmachines:
- name: controller
  image: red-hat-mbu/automation-controller
  shell: /bin/su - rhel -s /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-4
azure_subscriptions:
- name: aapazurelab
  roles:
  - Contributor
  - User Access Administrator
- name: azureviewer
  user_only: true
  roles:
  - Reader
