#!/bin/bash

#/usr/sbin/useradd -m -U -G google-sudoers -s /bin/bash devops

yum install -y yum-utils

yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

yum install -y docker-ce docker-ce-cli containerd.io

systemctl start docker

echo "devops ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/devops
