#!/bin/bash

USER=rhel

# Set the target directory and file
target_directory="/home/rhel/ansible-files"
target_file="${target_directory}/roles_cleanup.yml"

solve_file="/tmp/first-101/solve_19_system_setup_roles_cleanup.yml"

# Make sure solvers exist
/usr/bin/git clone https://github.com/leogallego/instruqt-wyfp-2024-solve.git /tmp/first-101


## CLEAN UP


## Copy solved playbook file
cp $solve_file $target_file

## Copy apache role directory
chown $USER:$USER -R $target_directory

## Run solve playbook
cd $target_directory
ansible-navigator run $target_file -m stdout 