galaxy_info:
  author: Craig Brandt
  description: Manage Google Cloud resources

  issue_tracker_url: http://github.com/ansible/instruqt/issues

  license: MIT

  min_ansible_version: "2.13"

  platforms:
    - name: EL
      versions:
        - "9"

  galaxy_tags: []

dependencies: []
