#!/usr/bin/env python3

import subprocess
import os
import yaml
from shlex import quote
os.environ["ANSIBLE_STDOUT_CALLBACK"] = "community.general.yaml"

# Load extra_vars.yml
extra_vars_file = open("/tmp/setup-scripts/devops-controller/track_vars.yml")
parsed_extra_vars_file = yaml.load(extra_vars_file, yaml.loader.FullLoader)
