---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local

  collections:
    - awx.awx
    - redhat_cop.controller_configuration

  vars:
    controller_hostname: https://localhost:443
    controller_username: admin
    controller_password: ansible123!
    controller_validate_certs: false

    controller_credentials:
      - name: servicenow
        description: Credentials for ServiceNow
        organization: Default
        credential_type: servicenow.itsm 
        inputs:
          username: "{{ lookup('env', 'INSTRUQT_PARTICIPANT_ID') }}"
          password: "{{ lookup('env', 'INSTRUQT_PARTICIPANT_ID') }}"
  
  roles:
    - {role: redhat_cop.controller_configuration.credentials, when: controller_credentials is defined}
