---
- name: Creates SNOW cred in Controller
  hosts: localhost
  connection: local

  collections:
    - awx.awx

  tasks:
  - name: add snow credential
    awx.awx.credential:
      name: 'servicenow credential'
      organization: Default
      credential_type: servicenow.itsm
      controller_host: "https://{{ ansible_host }}"
      controller_username: admin
      controller_password: ansible123!
      validate_certs: false
      inputs:
        SN_USERNAME: "{{ lookup('env', 'INSTRUQT_PARTICIPANT_ID') }}"
        SN_PASSWORD: "{{ lookup('env', 'INSTRUQT_PARTICIPANT_ID') }}"
        SN_HOST: ansible.service-now.com
