#!/usr/bin/python3

import subprocess
import os
os.environ["ANSIBLE_STDOUT_CALLBACK"] = "community.general.yaml"

# Vars
setup_scripts_path="/tmp/setup-scripts/getting-started-mesh/"

# Setup high-availability
mesh_playground_setup = subprocess.run(["ansible-playbook", setup_scripts_path+"getting-started-mesh-setup.yml", "-i", setup_scripts_path+"inventory.ini", "-e", "@"+setup_scripts_path+"extra_vars.yml", "--tags", "auth-token,playground-setup"])