---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - command: packer build --force automation-controller.pkr.hcl
      register: iloverhel
      until: iloverhel is not failed
      retries: 20 
