---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - command: packer build --force automation-controller.pkr.hcl
      register: ihaterhel
      until: ihaterhel is not failed
      retries: 20 
