version: "3"
virtualmachines:
- name: cisco
  image: red-hat-mbu/cisco-ios-csr-1731
  machine_type: n1-standard-4
- name: code-server
  image: red-hat-mbu/ansible
  shell: /bin/su - rhel -s /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-4
