#!/bin/bash

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

touch /etc/sudoers.d/rhel_sudoers
echo "%rhel ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/rhel_sudoers
cp -a /root/.ssh/* /home/rhel/.ssh/.
chown -R rhel:rhel /home/rhel/.ssh

curl https://raw.githubusercontent.com/craig-br/instruqt/getting-started-controller-review/images/ansible/setup-scripts/getting-started-controller/getting-started-controller-setup.yml -o /tmp/setup-scripts/getting-started-controller-setup.yml

/bin/ansible-playbook /tmp/setup-scripts/getting-started-controller-setup.yml --tags install-packages