#!/bin/bash

if [ ! -d /home/devops/collections/ansible_collections/community/clock/plugins/modules ]; then
    echo "Collection community.clock is missing with modules directory. To continue create "modules" sub directory inside community.clock collection."
    exit 1
fi

if [ ! -f /home/devops/collections/ansible_collections/community/clock/plugins/modules/timezone.py ]; then
    echo "Collection community.clock is missing with timezone.py module file. To continue download timezone.py file."
    exit 1
fi