#!/usr/bin/env python3

import subprocess
import yaml
from shlex import quote
import os

os.environ["ANSIBLE_VAULT_PASSWORD_FILE"] = ".lightspeed-101_ansible_vault_password"
setup_scripts_path="/opt/setup-scripts/lightspeed-101/setup/"

# Change working dir
os.chdir(setup_scripts_path)
# Load extra_vars.yml
extra_vars_file = open("/opt/setup-scripts/lightspeed-101/setup/vars/track_vars.yml")
parsed_extra_vars_file = yaml.load(extra_vars_file, yaml.loader.FullLoader)

# Check sshd_config file entries
setup_sshd = subprocess.run(["ansible-navigator", "run",
                                setup_scripts_path + "lightspeed-101-lab_setup.yml", 
                                "-e", "check_mode=true",
                                "--tags", "check-generate-tasks-ssh",
                                "--mode", "stdout"])

if setup_sshd.returncode > 0:
    print ("FAIL: The SSH config is incorrect. Please make sure you've created the Playbook, commited and pushed the code to the repository, and run the 'Harden app servers' Job Template.")
    exit(1)