#!/usr/bin/env python3

import subprocess
import yaml
import shlex
import os
os.environ["ANSIBLE_CONFIG"] = "/opt/setup-scripts/devops-controller/ansible.cfg"

# Load extra_vars.yml
extra_vars_file = open("/opt/setup-scripts/devops-controller/track_vars.yml")
parsed_extra_vars_file = yaml.load(extra_vars_file, yaml.loader.FullLoader)

# Check if controller job ran successfully
jt_output = subprocess.run(["ansible-playbook", 
                            "/opt/setup-scripts/devops-controller/setup-devops-controller.yml",
                            "-e", "lab_jt_name="+shlex.quote("Configure Jenkins Job"),
                            "--tags", "update-pipeline-check"])

if jt_output.returncode > 0:
    print ( "FAIL: Please make sure you've run the Configure Jenkins Job in controller and it has completed successfully.")
    exit(1)