#!/usr/bin/env python3

import subprocess
import os
import yaml
from shlex import quote
os.environ["ANSIBLE_STDOUT_CALLBACK"] = "community.general.yaml"

# Vars
setup_scripts_path="/tmp/setup-scripts/getting-started-edge-lab"

# Load extra_vars.yml
extra_vars_file = open( setup_scripts_path + "/track_vars.yml")
parsed_extra_vars_file = yaml.load(extra_vars_file, yaml.loader.FullLoader)

# Setup inventory and job template
inv_output = subprocess.run(["ansible-playbook", setup_scripts_path + "/getting-started-edge-lab-setup.yml", 
                            "-e", "@" + setup_scripts_path + "/track_vars.yml",
                            "-i", setup_scripts_path + "/inventory.ini",
                            "-e", "lab_jt_name="+quote(parsed_extra_vars_file.get('lab_monitor_app_jt_name')),
                            "-e", "lab_jt_limit="+quote('monitors'),
                            "--tags", "install-monitor-app-setup"])
if inv_output.returncode > 0:
    print ( "FAIL: Unable to create controller object - " + quote(parsed_extra_vars_file.get('lab_monitor_app_jt_name') ) )
    exit(1)
