#!/bin/bash

USER=rhel

# Set the target directory and file
target_directory="/home/rhel/ansible-files"
target_file="${target_directory}/deploy_apache.yml.yml"

roles_dir="${target_directory}/roles"
apache_roles_dir="${roles_dir}/apache"

solve_dir="/tmp/first-101/solve_19_system_setup_roles"
solve_file="/tmp/first-101/solve_19_system_setup_roles.yml"


# Make sure solvers exist
/usr/bin/git clone https://github.com/leogallego/instruqt-wyfp-2024-solve.git /tmp/first-101



#################
## CHECK 

# Verify roles directory exists
if [ -d "$roles_dir" ]; then
    echo "Roles directory exists."
else
    errors+=("Error: Roles directory does not exist.")
fi

# Directory structure check
dirs=("defaults" "files" "handlers" "meta" "tasks" "templates" "tests" "vars")
for dir in "${dirs[@]}"; do
    if [ ! -d "${apache_roles_dir}/${dir}" ]; then
        errors+=("Error: Run the ansible-galaxy command to setup the roles dir structure.")
    fi
done


# Check if the target_file file exists
if [ -f "$target_file" ]; then
    # Read the content of the target_file and solve_file
    file_content=$(cat "$target_file")
    solve_content=$(cat "$solve_file")

    # Compare the content of the target_file file with the expected content
    if [ "$file_content" != "$solve_content" ]; then
        fail-message "The 'system_setup.yml' file does not have the proper content. Please check the file and try again."
    fi
else
    fail-message "The 'system_setup.yml' file does not exist in the specified directory."
fi

# Check vars/main.yml
# check tasks/main.yml
# Check handlers/main.yml
# Check index.html.j2

# Check for the existence and content of the vars/main.yml file
if [ -f "${apache_roles_dir}/vars/main.yml" ]; then
    # Read the content of the target_file and solve_file
    file_content=$(cat "${apache_roles_dir}/vars/main.yml")
    solve_content=$(cat "${solve_dir}/vars/main.yml")
    if [ "$file_content" != "$solve_content" ]; then
        echo "${apache_roles_dir}/vars/main.yml exists and has the correct content."
    else
        errors+=("${apache_roles_dir}/vars/main.yml has incorrect content.")
    fi
else
    errors+=("${apache_roles_dir}/vars/main.yml does not exist.")
fi

# Check for the existence and content of the tasks/main.yml file
if [ -f "${apache_roles_dir}/tasks/main.yml" ]; then
    # Read the content of the target_file and solve_file
    file_content=$(cat "${apache_roles_dir}/tasks/main.yml")
    solve_content=$(cat "${solve_dir}/tasks/main.yml")
    if [ "$file_content" != "$solve_content" ]; then
        echo "${apache_roles_dir}/tasks/main.yml exists and has the correct content."
    else
        errors+=("${apache_roles_dir}/tasks/main.yml has incorrect content.")
    fi
else
    errors+=("${apache_roles_dir}/tasks/main.yml does not exist.")
fi


# Check for the existence and content of the handlers/main.yml file
if [ -f "${apache_roles_dir}/handlers/main.yml" ]; then
    # Read the content of the target_file and solve_file
    file_content=$(cat "${apache_roles_dir}/handlers/main.yml")
    solve_content=$(cat "${solve_dir}/handlers/main.yml")
    if [ "$file_content" != "$solve_content" ]; then
        echo "${apache_roles_dir}/handlers/main.yml exists and has the correct content."
    else
        errors+=("${apache_roles_dir}/handlers/main.yml has incorrect content.")
    fi
else
    errors+=("${apache_roles_dir}/handlers/main.yml does not exist.")
fi


# Check for the existence and content of the templates/index.html.j2 file
if [ -f "${apache_roles_dir}/templates/index.html.j2" ]; then
    # Read the content of the target_file and solve_file
    file_content=$(cat "${apache_roles_dir}/templates/index.html.j2")
    solve_content=$(cat "${solve_dir}/templates/index.html.j2")
    if [ "$file_content" != "$solve_content" ]; then
        echo "${apache_roles_dir}/templates/index.html.j2 exists and has the correct content."
    else
        errors+=("${apache_roles_dir}/templates/index.html.j2 has incorrect content.")
    fi
else
    errors+=("${apache_roles_dir}/templates/index.html.j2 does not exist.")
fi

