#!/bin/bash

USER=rhel

# Set the target directory and file
target_directory="/home/rhel/ansible-files"
target_file="${target_directory}/deploy_apache.yml.yml"

roles_dir="${target_directory}/roles"
apache_roles_dir="${roles_dir}/apache"

solve_dir="/tmp/first-101/solve_19_system_setup_roles"
solve_file="/tmp/first-101/solve_19_system_setup_roles.yml"


# Make sure solvers exist
/usr/bin/git clone https://github.com/leogallego/instruqt-wyfp-2024-solve.git /tmp/first-101


## SOLVE EVERYTHING


## Copy solved playbook file
cp $solve_file $target_file

## Copy apache role directory
mkdir -p $roles_dir
cp -R $solve_dir $apache_roles_dir
chown $USER:$USER -R $target_directory

## Run solve playbook
cd $target_directory
ansible-navigator run $target_file -m stdout 

#### run solve playbook as $USER
####su - $USER -c 'cd ansible-files && ansible-navigator run system_setup.yml -m stdout'

