#!/bin/bash

## fix dns resolution in automation-controller rhel9 image
echo "search $_SANDBOX_ID.svc.cluster.local." >> /etc/resolv.conf

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

touch /etc/sudoers.d/rhel_sudoers
echo "%rhel ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/rhel_sudoers
cp -a /root/.ssh/* /home/rhel/.ssh/.
chown -R rhel:rhel /home/rhel/.ssh


## COMMENT CENTOS 
# dnf config-manager --disable rhui*,google*

# sudo bash -c 'cat >/etc/yum.repos.d/centos8-baseos.repo <<EOL
# [centos8-baseos]
# name=CentOS 8 Stream BaseOS
# baseurl=http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os
# enabled=1
# gpgcheck=0

# EOL
# cat /etc/yum.repos.d/centos8-baseos.repo'

# sudo bash -c 'cat >/etc/yum.repos.d/centos8-appstream.repo <<EOL
# [centos8-appstream]
# name=CentOS 8 Stream AppStream
# baseurl=http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/
# enabled=1
# gpgcheck=0

# EOL
# cat /etc/yum.repos.d/centos8-appstream.repo'
## END COMMENT CENTOS

## clean repo metadata and refresh
dnf config-manager --disable google*
dnf clean all
# dnf config-manager --enable rhui-rhel-8-for-x86_64-baseos-rhui-rpms
# dnf config-manager --enable rhui-rhel-8-for-x86_64-appstream-rhui-rpms
dnf makecache

#Install a package to build metadata of the repo and not need to wait during labs
#dnf install -y cups-filesystem

# stop web server
systemctl stop nginx

# make Dan Walsh weep: https://stopdisablingselinux.com/
setenforce 0