version: "2"
virtualmachines:
- name: controller
  image: red-hat-mbu/automation-controller
  shell: /bin/su - rhel -s /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-2
- name: host01
  image: red-hat-mbu/ansible
  shell: /bin/su - rhel -s /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
- name: host02
  image: red-hat-mbu/ansible
  shell: /bin/su - rhel -s /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
