#!/bin/bash

export ADMIN_CONTROLLER_USERNAME=`agent variable get ADMIN_CONTROLLER_USERNAME`
export ADMIN_CONTROLLER_PASSWORD=`agent variable get ADMIN_CONTROLLER_PASSWORD`

ansible-playbook -e "job_template_name='1 - Create incident (incident-create.yml)'" /tmp/check-jt-run.yml --tags solve