#!/bin/bash

export ADMIN_CONTROLLER_USERNAME=`agent variable get ADMIN_CONTROLLER_USERNAME`
export ADMIN_CONTROLLER_PASSWORD=`agent variable get ADMIN_CONTROLLER_PASSWORD`

ansible-playbook -e "job_template_name='5 - Query and close records by user (close-records-by-user.yml)'" /tmp/check-jt-run.yml --tags solve