#!/bin/bash
set -euxo pipefail

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

# Setup rhel user
cp -a /root/.ssh/* /home/rhel/.ssh/.
chown -R rhel:rhel /home/rhel/.ssh

# Download lab content for testing
# TRACK_SLUG="getting-started-mesh"
# SETUP_FILES=(inventory.ini getting-started-mesh-setup.yml track_vars.yml receptor.conf.j2 ansible.cfg)
# mkdir -p /opt/setup-scripts/"${TRACK_SLUG}"

# for file in ${SETUP_FILES[@]}; do
#   wget https://s3.us-east-1.amazonaws.com/tmm-instruqt-content.demoredhat.com.private/getting-started-mesh-dev/"${file}" --output-document /opt/setup-scripts/"${TRACK_SLUG}"/"${file}"
# done